# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLe3L1IoxdS-TKdRxMWVgWOkoKBuA7FQ
"""

from google.colab import files

uploaded = files.upload()
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Read the CSV file
df = pd.read_csv("attendance.csv")

# Fill missing attendance values with the mean
df["AttendancePercent"] = df["AttendancePercent"].fillna(
    df["AttendancePercent"].mean()
)

# Forward fill any remaining missing attendance values
df["AttendancePercent"] = df["AttendancePercent"].ffill()

# Fill missing semester values with the mode
df["Semester"] = df["Semester"].fillna(
    df["Semester"].mode()[0]
)

# Encode the Semester column
encoder = LabelEncoder()

df["Semester"] = encoder.fit_transform(df["Semester"])

# Display the processed DataFrame
print(df)